# 用来存放数据库的文件夹
cache_dir: ./data/
# 是否使用egenshin的cookie,只有查询水晶手账时使用
is_egenshin: False
# egenshin的uid.sqlite的绝对路径,例如C:\HoshinoBot\hoshino\modules\egenshin\data\uid.sqlite
# 留空则默认为 somepath\hoshino\modules\egenshin\data\uid.sqlite
egenshin_dir: 
# 必填
cookies:
  - your cookies
