# 用来存放数据库的文件夹
cache_dir: ./data/
# 是否使用egenshin的cookie,只有查询水晶手账时使用,
# 此版本尚未使用
is_egenshin: False
# egenshin的文件夹,填写绝对路径
# 留空则默认为 somepath\hoshino\modules\egenshin
# 此版本尚未使用
egenshin_dir: 
# 必填
cookies:
  - your cookies
